  [[main]]
  name = "About"
  identifier = "home"
  weight = 100
  url = "/about/"

  [[main]]
  name = "Resumé"
  weight = 200
  identifier = "resumé"
  url = "/resume/"

  [[main]]
  name = "Portfolio"
  weight = 300
  identifier = "portfolio"

  [[main]]
  name = "Contact"
  weight = 400
  identifier = "contact"
  url = "/contact/"

  [[main]]
  name = "Manuals and other documentation"
  weight = 510
  identifier = "manuals"
  url = "/user-manuals/"
  parent = "portfolio"  

  [[main]]
  name = "Help centers"
  weight = 520
  identifier = "help-center"
  url = "/help-centers/"
  parent = "portfolio"
