  [[main]]
  name = "Home"
  identifier = "home"
  weight = 100
  url = "/"

  [[main]]
  name = "Resumé"
  weight = 200
  identifier = "resume"
  url = "/resume/"

  [[main]]
  name = "Portfolio"
  weight = 300
  identifier = "portfolio"
  url = "/portfolio/"

  [[main]]
  name = "Technical documentation"
  weight = 410
  identifier = "technical-documentation"
  url = "/technical-documentation/"
  parent = "portfolio"  
