  [[main]]
  name = "About"
  identifier = "home"
  weight = 100
  url = "/about/"

  [[main]]
  name = "Resume"
  weight = 200
  identifier = "resume"
  url = "/resume/"

  [[main]]
  name = "Portfolio"
  weight = 300
  identifier = "portfolio"

  [[main]]
  name = "Posts"
  weight = 400
  identifier = "posts"
  url = "/post/"

  [[main]]
  name = "Contact"
  weight = 500
  identifier = "contact"
  url = "/contact/"

  [[main]]
  name = "User manuals"
  weight = 510
  identifier = "manuals"
  url = "/user-manuals/"
  parent = "portfolio"  

  [[main]]
  name = "Help centers"
  weight = 520
  identifier = "help-center"
  url = "/help-centers/"
  parent = "portfolio"
