  [[main]]
  name = "About"
  identifier = "about"
  weight = 100
  url = "/about"

  [[main]]
  name = "Resumé"
  weight = 200
  identifier = "resume"
  url = "/resume/"

  [[main]]
  name = "Portfolio"
  weight = 300
  identifier = "portfolio"
  url = "/portfolio/"

  [[main]]
  name = "Technical documentation"
  weight = 410
  identifier = "technical-documentation"
  url = "/technical-documentation/"
  parent = "portfolio"  

  [[main]]
  name = "Help centers"
  weight = 420
  identifier = "help-centers"
  url = "/help-centers/"
  parent = "portfolio"

  [[main]]
  name = "Contact"
  weight = 500
  identifier = "contact"
  url = "/contact/"